- name: Pull nginx proxy manager image
  community.docker.docker_image:
    name: jc21/nginx-proxy-manager:latest
    source: pull

- name: Run nginx proxy manager
  community.docker.docker_container:
    name: nginx-proxy-manager
    image: jc21/nginx-proxy-manager:latest
    state: started
    restart_policy: always
    ports:
      - '80:80'
      - '81:81'
      - '443:443'
    volumes:
      - ./data:/data
      - ./letsencrypt:/etc/letsencrypt