---
- name: Install Nginx
  apt:
    name: nginx
    state: present
  when: ansible_facts['os_family'] == 'Debian'
- name: Default Nginx site config
  template:
      src: site.conf.j2
      dest: /etc/nginx/sites-available/default.conf
      owner: root
      group: root
      mode: 0755
- name: Nginx default index page
  ansible.builtin.file:
    src: /etc/nginx/sites-available/default.conf
    dest: /etc/nginx/sites-enabled/default.conf
    owner: root
    group: root
    state: link
  notify:
    - Reload nginx configuration
- name: Generate index.html
  template:
      src: index.html.j2
      dest: /var/www/html/index.html
      owner: root
      group: root
      mode: 0755
  notify:
    - Reload nginx configuration
- name: Enable Nginx service
  systemd:
    name: nginx
    daemon_reload: yes
    enabled: yes
    state: started