- name: Pull dispatcher image
  community.docker.docker_image:
    name: fteychene/cloud-cadavre-exquis-dispatcher
    source: pull

- name: Run dispatcher
  community.docker.docker_container:
    name: application
    image: fteychene/cloud-cadavre-exquis-dispatcher
    state: started
    restart_policy: always
    ports:
     - "8080:8080"
    env:
      REGISTER_URLS: "http://192.168.33.12:8080"