- name: Pull register image
  community.docker.docker_image:
    name: fteychene/cloud-cadavre-exquis-register:1.0-SNAPSHOT
    source: pull

- name: Run register
  community.docker.docker_container:
    name: register
    image: fteychene/cloud-cadavre-exquis-register:1.0-SNAPSHOT
    state: started
    restart_policy: always
    ports:
     - "8081:8080"
    env:
      POSTGRESQL_ADDON_HOST: "141.95.111.83"
      POSTGRESQL_ADDON_PORT: "5432"
      POSTGRESQL_ADDON_DB: "register"
      POSTGRESQL_ADDON_USER: "test"
      POSTGRESQL_ADDON_PASSWORD: "password"
