- name: Run provider for verbs
  community.docker.docker_container:
    name: provider
    image: fteychene/cloud-cadavre-exquis-provider:1.0-SNAPSHOT
    state: started
    restart_policy: always
    restart: yes
    ports:
     - "8082:8080"
    env:
      REGISTER_URLS: "http://141.95.106.44:8081"
      WORD_TYPE: VERB
      ADVERTISER_URL: "http://141.95.110.78:8082"