- name: Pull postgres image
  community.docker.docker_image:
    name: postgres:13
    source: pull

- name: Run postgres
  community.docker.docker_container:
    name: postgres
    image: postgres:13
    state: started
    restart_policy: always
    environment:
      POSTGRES_USER: "test"
      POSTGRES_PASSWORD: "password"
      POSTGRES_DB: "register"
    ports:
     - "5432:5432"